# fly.toml app configuration file generated for dba-soh on 2025-06-17T11:44:42+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dba-soh'
primary_region = 'syd'

[build]
  builder = 'paketobuildpacks/builder:base'

[processes]
  app = 'python dbasoh.py'
  cron = 'python dbasoh.py'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
