# Triggering GitHub to register schedule again last time
name: Run Fly Cron Job

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-fly-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Run scheduled task
        run: flyctl machines run registry.fly.io/dba-soh:deployment-01JXXRYQH8Y9TEYW7HZYK1R398 python dbasoh.py -a dba-soh --region syd --rm
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
