name: Run Fly Cron Job

on:
  schedule:
    - cron: '0 3 * * *'  # 3 AM UTC (2 PM Sydney AEST)
  workflow_dispatch:

jobs:
  run-fly-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Run Fly Cron Process
        run: flyctl machines run -a dba-soh-summer-dew-9401 --region syd --process-group cron --rm
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
